// All countries with ISO alpha-2 code and flag emoji.
// Flag is derived from ISO code: each letter maps to a Regional Indicator Symbol.
export type Country = { name: string; code: string; flag: string };

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫" },
  { name: "Albania", code: "AL", flag: "🇦🇱" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿" },
  { name: "Andorra", code: "AD", flag: "🇦🇩" },
  { name: "Angola", code: "AO", flag: "🇦🇴" },
  { name: "Argentina", code: "AR", flag: "🇦🇷" },
  { name: "Armenia", code: "AM", flag: "🇦🇲" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿" },
  { name: "Bahamas", code: "BS", flag: "🇧🇸" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩" },
  { name: "Belarus", code: "BY", flag: "🇧🇾" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Belize", code: "BZ", flag: "🇧🇿" },
  { name: "Benin", code: "BJ", flag: "🇧🇯" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦" },
  { name: "Botswana", code: "BW", flag: "🇧🇼" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "Brunei", code: "BN", flag: "🇧🇳" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", flag: "🇧🇮" },
  { name: "Cambodia", code: "KH", flag: "🇰🇭" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲" },
  { name: "Canada", code: "CA", flag: "🇨🇦" },
  { name: "Cape Verde", code: "CV", flag: "🇨🇻" },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫" },
  { name: "Chad", code: "TD", flag: "🇹🇩" },
  { name: "Chile", code: "CL", flag: "🇨🇱" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Colombia", code: "CO", flag: "🇨🇴" },
  { name: "Congo", code: "CG", flag: "🇨🇬" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷" },
  { name: "Croatia", code: "HR", flag: "🇭🇷" },
  { name: "Cuba", code: "CU", flag: "🇨🇺" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { name: "DR Congo", code: "CD", flag: "🇨🇩" },
  { name: "Denmark", code: "DK", flag: "🇩🇰" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯" },
  { name: "Dominican Republic", code: "DO", flag: "🇩🇴" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨" },
  { name: "Egypt", code: "EG", flag: "🇪🇬" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻" },
  { name: "Eritrea", code: "ER", flag: "🇪🇷" },
  { name: "Estonia", code: "EE", flag: "🇪🇪" },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯" },
  { name: "Finland", code: "FI", flag: "🇫🇮" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Gabon", code: "GA", flag: "🇬🇦" },
  { name: "Gambia", code: "GM", flag: "🇬🇲" },
  { name: "Georgia", code: "GE", flag: "🇬🇪" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "Ghana", code: "GH", flag: "🇬🇭" },
  { name: "Greece", code: "GR", flag: "🇬🇷" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹" },
  { name: "Guinea", code: "GN", flag: "🇬🇳" },
  { name: "Haiti", code: "HT", flag: "🇭🇹" },
  { name: "Honduras", code: "HN", flag: "🇭🇳" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Iceland", code: "IS", flag: "🇮🇸" },
  { name: "India", code: "IN", flag: "🇮🇳" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩" },
  { name: "Iran", code: "IR", flag: "🇮🇷" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶" },
  { name: "Ireland", code: "IE", flag: "🇮🇪" },
  { name: "Israel", code: "IL", flag: "🇮🇱" },
  { name: "Italy", code: "IT", flag: "🇮🇹" },
  { name: "Ivory Coast", code: "CI", flag: "🇨🇮" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲" },
  { name: "Japan", code: "JP", flag: "🇯🇵" },
  { name: "Jordan", code: "JO", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿" },
  { name: "Kenya", code: "KE", flag: "🇰🇪" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼" },
  { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬" },
  { name: "Laos", code: "LA", flag: "🇱🇦" },
  { name: "Latvia", code: "LV", flag: "🇱🇻" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧" },
  { name: "Liberia", code: "LR", flag: "🇱🇷" },
  { name: "Libya", code: "LY", flag: "🇱🇾" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬" },
  { name: "Malawi", code: "MW", flag: "🇲🇼" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾" },
  { name: "Mali", code: "ML", flag: "🇲🇱" },
  { name: "Malta", code: "MT", flag: "🇲🇹" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺" },
  { name: "Mexico", code: "MX", flag: "🇲🇽" },
  { name: "Moldova", code: "MD", flag: "🇲🇩" },
  { name: "Mongolia", code: "MN", flag: "🇲🇳" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪" },
  { name: "Morocco", code: "MA", flag: "🇲🇦" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲" },
  { name: "Namibia", code: "NA", flag: "🇳🇦" },
  { name: "Nepal", code: "NP", flag: "🇳🇵" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿" },
  { name: "Nicaragua", code: "NI", flag: "🇳🇮" },
  { name: "Niger", code: "NE", flag: "🇳🇪" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬" },
  { name: "North Korea", code: "KP", flag: "🇰🇵" },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰" },
  { name: "Norway", code: "NO", flag: "🇳🇴" },
  { name: "Oman", code: "OM", flag: "🇴🇲" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰" },
  { name: "Palestine", code: "PS", flag: "🇵🇸" },
  { name: "Panama", code: "PA", flag: "🇵🇦" },
  { name: "Papua New Guinea", code: "PG", flag: "🇵🇬" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾" },
  { name: "Peru", code: "PE", flag: "🇵🇪" },
  { name: "Philippines", code: "PH", flag: "🇵🇭" },
  { name: "Poland", code: "PL", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Qatar", code: "QA", flag: "🇶🇦" },
  { name: "Romania", code: "RO", flag: "🇷🇴" },
  { name: "Russia", code: "RU", flag: "🇷🇺" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
  { name: "Senegal", code: "SN", flag: "🇸🇳" },
  { name: "Serbia", code: "RS", flag: "🇷🇸" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱" },
  { name: "Singapore", code: "SG", flag: "🇸🇬" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮" },
  { name: "Somalia", code: "SO", flag: "🇸🇴" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦" },
  { name: "South Korea", code: "KR", flag: "🇰🇷" },
  { name: "South Sudan", code: "SS", flag: "🇸🇸" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰" },
  { name: "Sudan", code: "SD", flag: "🇸🇩" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭" },
  { name: "Syria", code: "SY", flag: "🇸🇾" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼" },
  { name: "Tajikistan", code: "TJ", flag: "🇹🇯" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿" },
  { name: "Thailand", code: "TH", flag: "🇹🇭" },
  { name: "Togo", code: "TG", flag: "🇹🇬" },
  { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳" },
  { name: "Turkey", code: "TR", flag: "🇹🇷" },
  { name: "Turkmenistan", code: "TM", flag: "🇹🇲" },
  { name: "Uganda", code: "UG", flag: "🇺🇬" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { name: "United States", code: "US", flag: "🇺🇸" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "UZ", flag: "🇺🇿" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳" },
  { name: "Yemen", code: "YE", flag: "🇾🇪" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
];

// City + state suggestions: a broad list covering major global cities.
// Format: "City, State/Region"
export const CITY_SUGGESTIONS: string[] = [
  // USA
  "New York, New York", "Brooklyn, New York", "Manhattan, New York", "Bronx, New York",
  "Queens, New York", "Harlem, New York", "Bushwick, New York", "Williamsburg, New York",
  "Los Angeles, California", "San Francisco, California", "Oakland, California",
  "San Diego, California", "Sacramento, California", "Long Beach, California",
  "Chicago, Illinois", "Houston, Texas", "Dallas, Texas", "Austin, Texas",
  "San Antonio, Texas", "Phoenix, Arizona", "Philadelphia, Pennsylvania",
  "San Jose, California", "Jacksonville, Florida", "Miami, Florida", "Orlando, Florida",
  "Tampa, Florida", "Atlanta, Georgia", "Boston, Massachusetts", "Seattle, Washington",
  "Denver, Colorado", "Nashville, Tennessee", "Portland, Oregon", "Las Vegas, Nevada",
  "Detroit, Michigan", "Baltimore, Maryland", "Louisville, Kentucky", "Memphis, Tennessee",
  "Minneapolis, Minnesota", "New Orleans, Louisiana", "Cleveland, Ohio", "Columbus, Ohio",
  "Indianapolis, Indiana", "Pittsburgh, Pennsylvania", "Charlotte, North Carolina",
  "Raleigh, North Carolina", "Richmond, Virginia", "Washington, District of Columbia",
  // UK
  "London, England", "Manchester, England", "Birmingham, England", "Leeds, England",
  "Liverpool, England", "Bristol, England", "Sheffield, England", "Newcastle, England",
  "Nottingham, England", "Edinburgh, Scotland", "Glasgow, Scotland", "Cardiff, Wales",
  "Belfast, Northern Ireland",
  // Europe
  "Paris, Île-de-France", "Marseille, Provence", "Lyon, Auvergne-Rhône-Alpes",
  "Toulouse, Occitanie", "Nice, Provence", "Bordeaux, Nouvelle-Aquitaine",
  "Berlin, Berlin", "Hamburg, Hamburg", "Munich, Bavaria", "Cologne, North Rhine-Westphalia",
  "Frankfurt, Hesse", "Stuttgart, Baden-Württemberg", "Düsseldorf, North Rhine-Westphalia",
  "Leipzig, Saxony", "Dresden, Saxony", "Kreuzberg, Berlin", "Prenzlauer Berg, Berlin",
  "Madrid, Community of Madrid", "Barcelona, Catalonia", "Valencia, Valencian Community",
  "Seville, Andalusia", "Bilbao, Basque Country", "Amsterdam, North Holland",
  "Rotterdam, South Holland", "The Hague, South Holland",
  "Rome, Lazio", "Milan, Lombardy", "Naples, Campania", "Turin, Piedmont",
  "Florence, Tuscany", "Venice, Veneto", "Bologna, Emilia-Romagna",
  "Lisbon, Lisbon", "Porto, Porto",
  "Vienna, Vienna", "Graz, Styria", "Zürich, Zurich", "Geneva, Geneva", "Basel, Basel-City",
  "Brussels, Brussels", "Antwerp, Antwerp", "Oslo, Oslo", "Bergen, Vestland",
  "Stockholm, Stockholm", "Gothenburg, Västra Götaland", "Copenhagen, Capital Region",
  "Helsinki, Uusimaa", "Warsaw, Masovian", "Kraków, Lesser Poland",
  "Prague, Prague", "Bratislava, Bratislava", "Budapest, Budapest",
  "Bucharest, Ilfov", "Sofia, Sofia City", "Athens, Attica",
  "Zagreb, Zagreb", "Belgrade, Belgrade", "Sarajevo, Federation of B&H",
  "Kyiv, Kyiv", "Lviv, Lviv", "Odessa, Odessa",
  "Moscow, Moscow", "Saint Petersburg, Leningrad Oblast",
  // Asia
  "Tokyo, Tokyo", "Osaka, Osaka", "Kyoto, Kyoto", "Yokohama, Kanagawa",
  "Nagoya, Aichi", "Koenji, Tokyo", "Shibuya, Tokyo", "Shinjuku, Tokyo",
  "Seoul, Seoul", "Busan, Busan", "Incheon, Incheon", "Hongdae, Seoul",
  "Beijing, Beijing", "Shanghai, Shanghai", "Guangzhou, Guangdong",
  "Shenzhen, Guangdong", "Chengdu, Sichuan", "Wuhan, Hubei",
  "Hong Kong, Hong Kong", "Taipei, Taipei",
  "Bangkok, Bangkok", "Chiang Mai, Chiang Mai",
  "Singapore, Singapore",
  "Kuala Lumpur, Federal Territory", "Penang, Penang",
  "Jakarta, Jakarta", "Bali, Bali", "Yogyakarta, Special Region of Yogyakarta",
  "Mumbai, Maharashtra", "Delhi, Delhi", "Bangalore, Karnataka",
  "Hyderabad, Telangana", "Chennai, Tamil Nadu", "Kolkata, West Bengal",
  "Lahore, Punjab", "Karachi, Sindh", "Dhaka, Dhaka",
  "Kathmandu, Bagmati", "Colombo, Western Province",
  "Hanoi, Hanoi", "Ho Chi Minh City, Ho Chi Minh",
  "Manila, Metro Manila", "Cebu City, Cebu",
  "Phnom Penh, Phnom Penh", "Yangon, Yangon",
  "Dubai, Dubai", "Abu Dhabi, Abu Dhabi", "Riyadh, Riyadh", "Jeddah, Mecca",
  "Tehran, Tehran", "Istanbul, Istanbul", "Ankara, Ankara",
  "Tel Aviv, Tel Aviv", "Jerusalem, Jerusalem",
  "Beirut, Beirut", "Amman, Amman", "Baghdad, Baghdad",
  // Africa
  "Lagos, Lagos", "Abuja, Federal Capital Territory", "Ibadan, Oyo",
  "Yaba, Lagos", "Victoria Island, Lagos",
  "Cairo, Cairo Governorate", "Alexandria, Alexandria Governorate",
  "Nairobi, Nairobi County", "Mombasa, Mombasa County",
  "Accra, Greater Accra", "Kumasi, Ashanti",
  "Dakar, Dakar", "Abidjan, Lagunes",
  "Addis Ababa, Addis Ababa", "Kampala, Kampala",
  "Dar es Salaam, Dar es Salaam", "Kigali, Kigali",
  "Casablanca, Grand Casablanca", "Marrakech, Marrakesh-Safi",
  "Johannesburg, Gauteng", "Cape Town, Western Cape",
  "Durban, KwaZulu-Natal", "Pretoria, Gauteng",
  "Kinshasa, Kinshasa", "Luanda, Luanda",
  // Latin America
  "São Paulo, São Paulo", "Rio de Janeiro, Rio de Janeiro",
  "Vila Madalena, São Paulo", "Pinheiros, São Paulo",
  "Buenos Aires, Buenos Aires", "Córdoba, Córdoba", "Rosario, Santa Fe",
  "Mexico City, Mexico City", "Guadalajara, Jalisco", "Monterrey, Nuevo León",
  "Roma Norte, Mexico City", "Condesa, Mexico City", "Coyoacán, Mexico City",
  "Bogotá, Cundinamarca", "Medellín, Antioquia", "Cali, Valle del Cauca",
  "Lima, Lima", "Cusco, Cusco",
  "Santiago, Santiago Metropolitan", "Valparaíso, Valparaíso",
  "Caracas, Capital District", "Havana, La Habana",
  "San José, San José", "Guatemala City, Guatemala",
  // Oceania
  "Sydney, New South Wales", "Melbourne, Victoria", "Brisbane, Queensland",
  "Perth, Western Australia", "Adelaide, South Australia",
  "Auckland, Auckland", "Wellington, Wellington", "Christchurch, Canterbury",
];
